//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionStatus complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="progress">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}short">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="finalStatus" type="{http://uri.etsi.org/m2m}FinalStatus"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionStatus", propOrder = {
        "action",
        "progress",
        "finalStatus"
})
@XmlRootElement
public class ActionStatus {

    @XmlElement(namespace = "", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String action;
    @XmlElement(namespace = "")
    protected short progress;
    @XmlElement(namespace = "", required = true)
    protected FinalStatus finalStatus;

    /**
     * Gets the value of the action property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the progress property.
     *
     */
    public short getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     *
     */
    public void setProgress(short value) {
        this.progress = value;
    }

    /**
     * Gets the value of the finalStatus property.
     *
     * @return
     *     possible object is
     *     {@link FinalStatus }
     *
     */
    public FinalStatus getFinalStatus() {
        return finalStatus;
    }

    /**
     * Sets the value of the finalStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link FinalStatus }
     *
     */
    public void setFinalStatus(FinalStatus value) {
        this.finalStatus = value;
    }

    public String toString() {
        return "ActionStatus [action=" + action + ", progress=" + progress
                + ", finalStatus=" + finalStatus + "]";
    }

}
