//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Applications complex type.
 *
 * <p> Applications resource is a collection of {@link Application} resources which
 * are registered to the hosting SCL represented by the {@link SclBase} resource.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Applications">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationAnncCollection" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}mgmtObjsReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */

@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement
public class Applications extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    protected NamedReferenceCollection applicationCollection;
    protected NamedReferenceCollection applicationAnncCollection;
    @XmlSchemaType(name = "anyURI")
    protected String subscriptionsReference;
    @XmlSchemaType(name = "anyURI")
    protected String mgmtObjsReference;

    /**
     * Gets the value of the creationTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the lastModifiedTime property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the lastModifiedTime property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the applicationCollection property.
     *
     * @return
     *     possible object is
     *     {@link NamedReferenceCollection }
     *
     */
    public NamedReferenceCollection getApplicationCollection() {
        if(applicationCollection == null){
            applicationCollection = new NamedReferenceCollection();
        }
        return applicationCollection;
    }

    /**
     * Sets the value of the applicationCollection property.
     *
     * @param value
     *     allowed object is
     *     {@link NamedReferenceCollection }
     *
     */
    public void setApplicationCollection(NamedReferenceCollection value) {
        this.applicationCollection = value;
    }

    /**
     * Gets the value of the applicationAnncCollection property.
     *
     * @return
     *     possible object is
     *     {@link NamedReferenceCollection }
     *
     */
    public NamedReferenceCollection getApplicationAnncCollection() {
        if(applicationAnncCollection == null){
            applicationAnncCollection = new NamedReferenceCollection();
        }
        return applicationAnncCollection;

    }

    /**
     * Sets the value of the applicationAnncCollection property.
     *
     * @param value
     *     allowed object is
     *     {@link NamedReferenceCollection }
     *
     */
    public void setApplicationAnncCollection(NamedReferenceCollection value) {
        this.applicationAnncCollection = value;
    }

    /**
     * Gets the value of the subscriptionsReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
        return subscriptionsReference;
    }

    /**
     * Sets the value of the subscriptionsReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    /**
     * Gets the value of the mgmtObjsReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMgmtObjsReference() {
        return mgmtObjsReference;
    }

    /**
     * Sets the value of the mgmtObjsReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMgmtObjsReference(String value) {
        this.mgmtObjsReference = value;
    }

    public String toString() {
        return "Applications [accessRightID=" + accessRightID
                + ", creationTime=" + creationTime + ", lastModifiedTime="
                + lastModifiedTime + ", applicationCollection="
                + applicationCollection + ", applicationAnncCollection="
                + applicationAnncCollection + ", subscriptionsReference="
                + subscriptionsReference + ", mgmtObjsReference="
                + mgmtObjsReference + ", uri=" + uri + "]";
    }
}
