//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.01.25 at 05:56:27 PM CET
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactInfo complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ContactInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://uri.etsi.org/m2m}contactURI"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}other"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactInfo", propOrder = {
        "contactURI",
        "other"
})
public class ContactInfo {

    @XmlSchemaType(name = "anyURI")
    protected String contactURI;
    protected Object other;

    /**
     * Gets the value of the contactURI property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContactURI() {
        return contactURI;
    }

    /**
     * Sets the value of the contactURI property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContactURI(String value) {
        this.contactURI = value;
    }

    /**
     * Gets the value of the other property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setOther(Object value) {
        this.other = value;
    }

    public String toString() {
        return "ContactInfo [contactURI=" + contactURI + ", other=" + other
                + "]";
    }

}
