//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.24 at 02:39:25 AM CEST
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;


/**
 * <p>Java Class for LocationContainer complex type.
 *
 * <p>LocationContainer resource represents a container for the location information
 * of a M2M entity (e.g. M2M Device/Gateway). The location information may be generated
 * by a Device/Gateway application or provided by location server in the network domain.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="LocationContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://uri.etsi.org/m2m}Container">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}locationContainerType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)

public class LocationContainer extends Container {

    @XmlElement(required = true)
    protected LocationContainerType locationContainerType;

    /**
     * Gets the value of the property locationContainerType.
     *
     * @return
     *     possible object is
     *     {@link LocationContainerType }
     *
     */
    public LocationContainerType getLocationContainerType() {
        return locationContainerType;
    }

    /**
     * Sets the value of the property locationContainerType.
     *
     * @param value
     *     allowed object is
     *     {@link LocationContainerType }
     *
     */
    public void setLocationContainerType(LocationContainerType value) {
        this.locationContainerType = value;
    }

}
