//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.06.24 at 02:52:11 AM CEST
//


package org.eclipse.om2m.commons.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java Class for SclBase complex type.
 *
 * <p>SclBase resource contains all other resources of the hosting SCL.
 * An SclBase is the root of all other resources it contains.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SclBase">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightID" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}searchStrings" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}creationTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}lastModifiedTime" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}aPocHandling" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}sclsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}applicationsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}containersReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}groupsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}accessRightsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}subscriptionsReference" minOccurs="0"/>
 *         &lt;element ref="{http://uri.etsi.org/m2m}discoveryReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)

public class SclBase extends Resource {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedTime;
    protected APocHandling aPocHandling;
    @XmlSchemaType(name = "anyURI")
    protected String sclsReference;
    @XmlSchemaType(name = "anyURI")
    protected String applicationsReference;
    @XmlSchemaType(name = "anyURI")
    protected String containersReference;
    @XmlSchemaType(name = "anyURI")
    protected String groupsReference;
    @XmlSchemaType(name = "anyURI")
    protected String accessRightsReference;
    @XmlSchemaType(name = "anyURI")
    protected String subscriptionsReference;
    @XmlSchemaType(name = "anyURI")
    protected String discoveryReference;

    public SclBase() {
        super();
    }

    /**
     * Gets the value of the property creationTime.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */

    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the property creationTime.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */

    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

    /**
     * Gets the value of the property lastModifiedTime.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */

    public XMLGregorianCalendar getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Sets the value of the property lastModifiedTime.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */

    public void setLastModifiedTime(XMLGregorianCalendar value) {
        this.lastModifiedTime = value;
    }

    /**
     * Gets the value of the property aPocHandling.
     *
     * @return
     *     possible object is
     *     {@link APocHandling }
     *
     */
    public APocHandling getAPocHandling() {
        return aPocHandling;
    }

    /**
     * Sets the value of the property aPocHandling.
     *
     * @param value
     *     allowed object is
     *     {@link APocHandling }
     *
     */
    public void setAPocHandling(APocHandling value) {
        this.aPocHandling = value;
    }

    /**
     * Gets the value of the property sclsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSclsReference() {
        return sclsReference;
    }

    /**
     * Sets the value of the property sclsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSclsReference(String value) {
        this.sclsReference = value;
    }

    /**
     * Gets the value of the property applicationsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getApplicationsReference() {
        return applicationsReference;
    }

    /**
     * Sets the value of the property applicationsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setApplicationsReference(String value) {
        this.applicationsReference = value;
    }

    /**
     * Gets the value of the property containersReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getContainersReference() {
        return containersReference;
    }

    /**
     * Sets the value of the property containersReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setContainersReference(String value) {
        this.containersReference = value;
    }

    /**
     * Gets the value of the property groupsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGroupsReference() {
        return groupsReference;
    }

    /**
     * Sets the value of the property groupsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGroupsReference(String value) {
        this.groupsReference = value;
    }

    /**
     * Gets the value of the property accessRightsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccessRightsReference() {
        return accessRightsReference;
    }

    /**
     * Sets the value of the property accessRightsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccessRightsReference(String value) {
        this.accessRightsReference = value;
    }

    /**
     * Gets the value of the property subscriptionsReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubscriptionsReference() {
        return subscriptionsReference;
    }

    /**
     * Sets the value of the property subscriptionsReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubscriptionsReference(String value) {
        this.subscriptionsReference = value;
    }

    /**
     * Gets the value of the property discoveryReference.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDiscoveryReference() {
        return discoveryReference;
    }

    /**
     * Sets the value of the property discoveryReference.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDiscoveryReference(String value) {
        this.discoveryReference = value;
    }

    @Override
    public String toString() {
        return "SclBase [accessRightID=" + accessRightID + ", searchStrings="
                + searchStrings + ", creationTime=" + creationTime
                + ", lastModifiedTime=" + lastModifiedTime + ", aPocHandling="
                + aPocHandling + ", sclsReference=" + sclsReference
                + ", applicationsReference=" + applicationsReference
                + ", containersReference=" + containersReference
                + ", groupsReference=" + groupsReference
                + ", accessRightsReference=" + accessRightsReference
                + ", subscriptionsReference=" + subscriptionsReference
                + ", discoveryReference=" + discoveryReference + ", uri=" + uri
                + "]";
    }



}
